accent: "#f8f8f2"
background: "#2b2b2b"
foreground: "#eeeeee"
details: "darker"
terminal_colors:
  normal:
    black: "#2b2b2b"
    red: "#ffa07a"
    green: "#abe338"
    yellow: "#ffd700"
    blue: "#00e0e0"
    magenta: "#dcc6e0"
    cyan: "#00e0e0"
    white: "#f8f8f2"
  bright:
    black: "#2b2b2b"
    red: "#ffa07a"
    green: "#abe338"
    yellow: "#ffd700"
    blue: "#00e0e0"
    magenta: "#dcc6e0"
    cyan: "#00e0e0"
    white: "#f8f8f2"
