# Accent color for UI elements
accent: "#aa5d00"
# Terminal background color
background: "#fefefe"
# Whether the theme is lighter or darker.
details: lighter
# The foreground color.
foreground: "#696969"
# Ansi escape colors.
terminal_colors:
  bright:
    black: "#545454"
    red: "#d91e18"
    green: "#008000"
    yellow: "#af5f00"
    blue: "#3a94c5"
    magenta: "#df69ba"
    cyan: "#007299"
    white: "#696969"
  normal:
    black: "#545454"
    red: "#d91e18"
    green: "#008000"
    yellow: "#af5f00"
    blue: "#3a94c5"
    magenta: "#df69ba"
    cyan: "#007299"
    white: "#696969"
