[ -d "/opt/homebrew/share/zsh-autosuggestions/" ] && source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh \
                                                  || source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

[ -d "/opt/homebrew/share/zsh-syntax-highlighting/highlighters" ] && export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/opt/homebrew/share/zsh-syntax-highlighting/highlighters \
                                                                  || export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/usr/local/share/zsh-syntax-highlighting/highlighters

[ -d "/opt/homebrew/share/zsh-autosuggestions/" ] && source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh \
                                                  || source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"
# fox, tonotdo, agnoster
COMPLETION_WAITING_DOTS="true"

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
plugins=(git composer sublime macos wp-cli vi-mode yarn vscode)

source $ZSH/oh-my-zsh.sh

#--------------------------------------------------------------------------
# Configuration
#--------------------------------------------------------------------------

export EDITOR=vim
export GIT_EDITOR=vim
export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket
export ARTISAN_OPEN_ON_MAKE_EDITOR=nvr

# export MANPATH="/usr/local/man:$MANPATH"
export PATH="/opt/homebrew/opt/php@8.1/sbin:$PATH"
export PATH="/Users/zacharytaylor/.local/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export PATH=$PATH:~/.composer/vendor/bin
export PATH=$HOME/.composer/vendor/bin:$HOME/bin:/usr/local/bin:$PATH

export PATH="/opt/homebrew/opt/php@8.1/bin:$PATH"
export PATH="/opt/homebrew/opt/php@8.1/sbin:$PATH"
export PATH=$PATH:$NVM_DIR/versions/node/node_modules/.bin

export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
export PATH="~/.local/bin/lvim:$PATH"

# echo 'export PATH="/opt/homebrew/opt/php@8.1/bin:$PATH"' >> ~/.zshrc
# echo 'export PATH="/opt/homebrew/opt/php@8.1/sbin:$PATH"' >> ~/.zshrc

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='lvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"
export XDEBUG_CONFIG="idekey=VSCODE"

#--------------------------------------------------------------------------
# Aliases
#--------------------------------------------------------------------------
command_exists () {
  hash "$1" 2> /dev/null
}
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias nvim="lvim"
alias vim="nvim"
alias v="nvim"
alias zcfg="vim ~/.zshrc"
alias zrld="source ~/.zshrc"
alias scfg="vim ~/.ssh/config"
alias hcfg="sudo vim /private/etc/hosts"
alias dcfg="vim ~/Repos/dotfiles"
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'
# alias ls="exa -lag --header"
alias exa="/opt/homebrew/bin/exa"
alias cdk="cd"" ~/Kinetic"
alias cdr="cd"" ~/Repos"
alias cdrd="cd"" ~/Repos/dotfiles"
alias home="cd ~"
alias ..="cd .."
alias lg="lazygit"
alias cduo="composer dump-autoload -o"
alias npmrw="npm run watch"
alias npmrd="npm run dev"
alias npmrp="npm run production"
alias dnsflush="sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder"
alias bigbois="find / -type f -size +1G -ls"
alias s="kitty +kitten ssh"
alias c="clear"
alias vsec="valet secure"
alias wpsr="wp search-replace"
alias vs="code"
alias vsc="code ."

# File listing options
alias lr='ls -R' # List files in sub-directories, recursivley
alias lf='ls -A | grep' # Use grep to find files
alias lc='find . -type f | wc -l' # Shows number of files
alias ld='ls -l | grep "^d"' # List directories only

# If exa installed, then use exa for some ls commands
if command_exists exa ; then
  alias l='exa -aF --icons' # Quick ls
  alias la='exa -aF --icons' # List all
  alias ll='exa -laF --icons' # Show details
  alias lm='exa -lahr --color-scale --icons -s=modified' # Recent
  alias lb='exa -lahr --color-scale --icons -s=size' # Largest / size
  alias tree='f() { exa -aF --tree -L=${1:-2} --icons };f'
else
  alias la='ls -A' # List all files/ includes hidden
  alias ll='ls -lAFh' # List all files, with full details
  alias lb='ls -lhSA' # List all files sorted by biggest
  alias lm='ls -tA -1' # List files sorted by last modified
fi

# Use color diff, if availible
if command_exists colordiff ; then
  alias diff='colordiff'
fi

# Find + manage aliases
alias al='alias | less' # List all aliases
alias as='alias | grep' # Search aliases
alias ar='unalias' # Remove given alias

# System Monitoring
# alias meminfo='free -m -l -t' # Show free and used memory
# alias memhog='ps -eo pid,ppid,cmd,%mem --sort=-%mem | head' # Processes consuming most mem
# alias cpuhog='ps -eo pid,ppid,cmd,%cpu --sort=-%cpu | head' # Processes consuming most cpu
# alias cpuinfo='lscpu' # Show CPU Info
# alias distro='cat /etc/*-release' # Show OS info
# alias ports='netstat -tulanp' # Show open ports

# Copy / pasting
alias cpwd='pwd | pbcopy' # Copy current path
alias pa='pbpaste' # Paste clipboard contents

# External Services
alias myip='curl icanhazip.com'
alias weather='curl wttr.in'
alias weather-short='curl "wttr.in?format=3"'
alias cheat='curl cheat.sh/'
alias tinyurl='curl -s "http://tinyurl.com/api-create.php?url='
alias joke='curl https://icanhazdadjoke.com'
alias hackernews='curl hkkr.in'
alias worldinternet='curl https://status.plaintext.sh/t'

# Random lolz
alias cls='clear;ls' # Clear and ls
alias plz="fc -l -1 | cut -d' ' -f2- | xargs sudo" # Re-run last cmd as root
alias yolo='git add .; git commit -m "YOLO"; git push origin master'
alias when='date' # Show date
alias whereami='pwd'
alias dog='cat'
alias gtfo='exit'

#--------------------------------------------------------------------------
# Miscellaneous
#--------------------------------------------------------------------------

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completionexport PATH="/opt/homebrew/opt/php@8.1/bin:$PATH"

up() { . up.sh "$1"; }
rep() { . rep.sh "$1"; }

function brew() {
  command brew "$@" 

  if [[ $* =~ "upgrade" ]] || [[ $* =~ "update" ]] || [[ $* =~ "outdated" ]]; then
    sketchybar --trigger brew_update
  fi
}

export GPG_TTY=$(tty)
eval "$(starship init zsh)"
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
export PATH="/opt/homebrew/opt/ruby/bin:/opt/homebrew/lib/ruby/gems/3.2.0/bin:$PATH"
eval "$(zoxide init zsh)"
eval "$(thefuck --alias)"
