-- vim.opt.clipboard = 'unnamedplus' -- Use Linux system clipboard
-- vim.opt.confirm = true -- ask for confirmation instead of erroring
-- vim.opt.undofile = true -- persistent undo
-- vim.opt.backup = true -- automatically save a backup file
-- vim.opt.backupdir:remove('.') -- keep backups out of the current directory
-- vim.opt.wildmode = 'longest:full,full' -- complete the longest common match, and allow tabbing the results to fully complete them
-- vim.opt.showmode = false
